package analyzer

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bobbydeveaux/pulse/internal/cocomo"
	"github.com/bobbydeveaux/pulse/internal/complexity"
	"github.com/bobbydeveaux/pulse/internal/duplication"
	"github.com/bobbydeveaux/pulse/internal/languages"
	"github.com/bobbydeveaux/pulse/internal/maintainability"
	"github.com/bobbydeveaux/pulse/internal/sloc"
	"github.com/bobbydeveaux/pulse/internal/types"
)

// skipDirs contains directories to always skip.
var skipDirs = map[string]bool{
	"node_modules": true, "vendor": true, ".git": true,
	"dist": true, "build": true, "__pycache__": true,
	"venv": true, ".venv": true, ".next": true, ".nuxt": true,
	"coverage": true, ".idea": true, ".vscode": true,
	"target": true, "bin": true, "obj": true,
}

// skipExts contains file extensions to skip.
var skipExts = map[string]bool{
	".min.js": true, ".min.css": true,
	".lock": true, ".sum": true,
	".png": true, ".jpg": true, ".jpeg": true, ".gif": true,
	".ico": true, ".svg": true, ".woff": true, ".woff2": true,
	".ttf": true, ".eot": true, ".mp3": true, ".mp4": true,
	".zip": true, ".tar": true, ".gz": true,
	".pdf": true, ".exe": true, ".dll": true, ".so": true,
	".pyc": true, ".class": true, ".o": true, ".a": true,
}

// generatedFilePatterns matches filenames that are typically generated code.
var generatedFilePatterns = []string{
	"_gen.go", "_generated.go", ".gen.go", ".generated.go",
	"generated.go", ".pb.go", ".pb.gw.go", "_string.go",
	"_mock.go", "mock_", "zz_generated",
	".generated.ts", ".generated.js",
}

// isGenerated checks if a file is generated code by name pattern or content marker.
func isGenerated(path string) bool {
	base := filepath.Base(path)

	// Check filename patterns
	for _, pattern := range generatedFilePatterns {
		if strings.Contains(base, pattern) || strings.HasPrefix(base, pattern) {
			return true
		}
	}

	// Check first few lines for generation markers
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for i := 0; i < 10 && scanner.Scan(); i++ {
		line := scanner.Text()
		if strings.Contains(line, "Code generated") ||
			strings.Contains(line, "DO NOT EDIT") ||
			strings.Contains(line, "auto-generated") ||
			strings.Contains(line, "AUTO GENERATED") ||
			strings.Contains(line, "automatically generated") ||
			strings.Contains(line, "This file was generated") ||
			strings.Contains(line, "generated by") {
			return true
		}
	}

	return false
}

// ExtraSkipDirs allows callers to add additional directories to skip.
var ExtraSkipDirs []string

// ignorePattern represents a single pattern from a .pulseignore file.
type ignorePattern struct {
	pattern string
	isDir   bool // true if the pattern ends with /
}

// loadPulseignore reads a .pulseignore file and returns parsed patterns.
// Returns nil (no error) if the file does not exist.
func loadPulseignore(root string) ([]ignorePattern, error) {
	path := filepath.Join(root, ".pulseignore")
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	defer f.Close()

	var patterns []ignorePattern
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasSuffix(line, "/") {
			patterns = append(patterns, ignorePattern{
				pattern: strings.TrimSuffix(line, "/"),
				isDir:   true,
			})
		} else {
			patterns = append(patterns, ignorePattern{
				pattern: line,
				isDir:   false,
			})
		}
	}
	return patterns, scanner.Err()
}

// matchesIgnorePattern checks whether a given path (relative to root) matches
// any of the parsed ignore patterns.
func matchesIgnorePattern(relPath string, info os.FileInfo, patterns []ignorePattern) bool {
	base := filepath.Base(relPath)
	for _, p := range patterns {
		if p.isDir {
			// Directory pattern: match if the relative path starts with the
			// directory name (i.e., the file is inside that directory) or if
			// we are looking at the directory entry itself.
			if info.IsDir() && (relPath == p.pattern || strings.HasPrefix(relPath, p.pattern+string(filepath.Separator))) {
				return true
			}
			if !info.IsDir() && (strings.HasPrefix(relPath, p.pattern+string(filepath.Separator))) {
				return true
			}
		} else {
			// Glob/file pattern: match against the base name of the file.
			if matched, _ := filepath.Match(p.pattern, base); matched {
				return true
			}
			// Also try matching against the full relative path.
			if matched, _ := filepath.Match(p.pattern, relPath); matched {
				return true
			}
		}
	}
	return false
}

// Analyze runs the full analysis pipeline on the given path.
func Analyze(root string) (*types.ProjectMetrics, error) {
	files, err := collectFiles(root)
	if err != nil {
		return nil, err
	}

	pm := &types.ProjectMetrics{}
	langMap := map[string]*types.LanguageSummary{}

	for _, path := range files {
		// SLOC counting
		counts, err := sloc.CountFile(path)
		if err != nil || counts.Language == "" {
			continue
		}

		// Complexity analysis
		funcs, err := complexity.AnalyzeFile(path)
		if err != nil {
			funcs = nil
		}

		// Set file path on each function
		for i := range funcs {
			if funcs[i].File == "" {
				funcs[i].File = path
			}
		}

		// Compute file-level maintainability from per-function MI
		var funcInputs []maintainability.FuncInput
		for _, f := range funcs {
			funcInputs = append(funcInputs, maintainability.FuncInput{
				SLOC:       f.SLOC,
				Cyclomatic: f.Cyclomatic,
			})
		}
		mi := maintainability.FileIndex(funcInputs, counts.SLOC)

		fm := types.FileMetrics{
			Path:               path,
			Language:           counts.Language,
			SLOC:               counts.SLOC,
			Comments:           counts.Comments,
			Blanks:             counts.Blanks,
			TotalLines:         counts.TotalLines,
			Functions:          funcs,
			MaintainabilityIdx: mi,
			Grade:              types.MaintainabilityGrade(mi),
		}

		pm.Files = append(pm.Files, fm)
		pm.TotalSLOC += counts.SLOC
		pm.TotalComments += counts.Comments
		pm.TotalBlanks += counts.Blanks
		pm.TotalLines += counts.TotalLines
		pm.TotalFiles++
		pm.TotalFunctions += len(funcs)

		// Aggregate per-language
		ls, ok := langMap[counts.Language]
		if !ok {
			ls = &types.LanguageSummary{Language: counts.Language}
			langMap[counts.Language] = ls
		}
		ls.Files++
		ls.SLOC += counts.SLOC
		ls.Comments += counts.Comments
		ls.Blanks += counts.Blanks
		ls.TotalLines += counts.TotalLines
	}

	// Language summaries sorted by SLOC
	for _, ls := range langMap {
		pm.LanguageSummaries = append(pm.LanguageSummaries, *ls)
	}
	sort.Slice(pm.LanguageSummaries, func(i, j int) bool {
		return pm.LanguageSummaries[i].SLOC > pm.LanguageSummaries[j].SLOC
	})

	// Aggregate function metrics
	totalCCN := 0
	totalCog := 0
	funcCount := 0
	for _, f := range pm.Files {
		for _, fn := range f.Functions {
			totalCCN += fn.Cyclomatic
			totalCog += fn.Cognitive
			funcCount++

			if fn.Cyclomatic > pm.MaxCyclomatic.Cyclomatic {
				pm.MaxCyclomatic = fn
			}
			if fn.Cognitive > pm.MaxCognitive.Cognitive {
				pm.MaxCognitive = fn
			}
		}
	}
	if funcCount > 0 {
		pm.AvgCyclomatic = float64(totalCCN) / float64(funcCount)
		pm.AvgCognitive = float64(totalCog) / float64(funcCount)
	}

	// Project-level maintainability = average of per-file MI scores
	if len(pm.Files) > 0 {
		totalMI := 0.0
		for _, f := range pm.Files {
			totalMI += f.MaintainabilityIdx
		}
		pm.MaintainabilityIdx = totalMI / float64(len(pm.Files))
	}
	pm.Grade = types.MaintainabilityGrade(pm.MaintainabilityIdx)

	// Duplication detection
	pm.Duplicates, pm.DuplicationPct = duplication.Detect(files)

	// COCOMO estimation
	est := cocomo.Calculate(pm.TotalSLOC)
	pm.COCOMOMonths = est.PersonMonths
	pm.COCOMOPersons = est.Persons
	pm.COCOMOCost = est.Cost

	return pm, nil
}

func collectFiles(root string) ([]string, error) {
	var files []string

	// Build combined skip dirs
	extraSkips := map[string]bool{}
	for _, d := range ExtraSkipDirs {
		extraSkips[d] = true
	}

	// Load .pulseignore patterns from the root directory
	ignorePatterns, err := loadPulseignore(root)
	if err != nil {
		return nil, fmt.Errorf("reading .pulseignore: %w", err)
	}

	err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // skip errors
		}

		// Compute path relative to root for ignore matching
		relPath, _ := filepath.Rel(root, path)

		if info.IsDir() {
			name := info.Name()
			if skipDirs[name] || extraSkips[name] {
				return filepath.SkipDir
			}
			// Check .pulseignore directory patterns
			if len(ignorePatterns) > 0 && relPath != "." {
				if matchesIgnorePattern(relPath, info, ignorePatterns) {
					return filepath.SkipDir
				}
			}
			return nil
		}

		// Check .pulseignore file patterns
		if len(ignorePatterns) > 0 {
			if matchesIgnorePattern(relPath, info, ignorePatterns) {
				return nil
			}
		}

		ext := filepath.Ext(path)
		if skipExts[ext] {
			return nil
		}

		// Check if it has a suffix like .min.js
		base := filepath.Base(path)
		if strings.Contains(base, ".min.") {
			return nil
		}

		// Only include files we know how to analyze
		if _, ok := languages.ByExtension(ext); !ok {
			return nil
		}

		// Skip generated files
		if isGenerated(path) {
			return nil
		}

		files = append(files, path)
		return nil
	})

	return files, err
}
